ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  "@parcel/watcher": false
  "@reown/appkit": false
  bigint-buffer: false
  bufferutil: false
  keccak: false
  protobufjs: true
  sharp: false
  tiny-secp256k1: set this to true or false
  unrs-resolver: false
  utf-8-validate: false


lockfileIncludeTarballUrl: true

minimumReleaseAgeExclude:
  - '@GestLabs2-0/stayke-config'
  - '@GestLabs2-0/stayke-core'
  - '@GestLabs2-0/stayke-disputes'
  - '@GestLabs2-0/stayke-escrow'
  - '@GestLabs2-0/stayke-treasury'
