import { SelectMenuOption } from "@/src/types/SelectMenuOption";

export const COUNTRIES: SelectMenuOption[] = [
  { value: "AF", title: "Afghanistan", label: "🇦🇫" },
  { value: "AL", title: "Albania", label: "🇦🇱" },
  { value: "DZ", title: "Algeria", label: "🇩🇿" },
  { value: "AR", title: "Argentina", label: "🇦🇷" },
  { value: "AU", title: "Australia", label: "🇦🇺" },
  { value: "AT", title: "Austria", label: "🇦🇹" },
  { value: "BE", title: "Belgium", label: "🇧🇪" },
  { value: "BO", title: "Bolivia", label: "🇧🇴" },
  { value: "BR", title: "Brazil", label: "🇧🇷" },
  { value: "CA", title: "Canada", label: "🇨🇦" },
  { value: "CL", title: "Chile", label: "🇨🇱" },
  { value: "CN", title: "China", label: "🇨🇳" },
  { value: "CO", title: "Colombia", label: "🇨🇴" },
  { value: "CR", title: "Costa Rica", label: "🇨🇷" },
  { value: "CU", title: "Cuba", label: "🇨🇺" },
  { value: "CZ", title: "Czech Republic", label: "🇨🇿" },
  { value: "DK", title: "Denmark", label: "🇩🇰" },
  { value: "DO", title: "Dominican Republic", label: "🇩🇴" },
  { value: "EC", title: "Ecuador", label: "🇪🇨" },
  { value: "EG", title: "Egypt", label: "🇪🇬" },
  { value: "SV", title: "El Salvador", label: "🇸🇻" },
  { value: "FR", title: "France", label: "🇫🇷" },
  { value: "DE", title: "Germany", label: "🇩🇪" },
  { value: "GT", title: "Guatemala", label: "🇬🇹" },
  { value: "HN", title: "Honduras", label: "🇭🇳" },
  { value: "HK", title: "Hong Kong", label: "🇭🇰" },
  { value: "IN", title: "India", label: "🇮🇳" },
  { value: "ID", title: "Indonesia", label: "🇮🇩" },
  { value: "IE", title: "Ireland", label: "🇮🇪" },
  { value: "IL", title: "Israel", label: "🇮🇱" },
  { value: "IT", title: "Italy", label: "🇮🇹" },
  { value: "JP", title: "Japan", label: "🇯🇵" },
  { value: "MX", title: "Mexico", label: "🇲🇽" },
  { value: "NL", title: "Netherlands", label: "🇳🇱" },
  { value: "NZ", title: "New Zealand", label: "🇳🇿" },
  { value: "NI", title: "Nicaragua", label: "🇳🇮" },
  { value: "NG", title: "Nigeria", label: "🇳🇬" },
  { value: "NO", title: "Norway", label: "🇳🇴" },
  { value: "PA", title: "Panama", label: "🇵🇦" },
  { value: "PY", title: "Paraguay", label: "🇵🇾" },
  { value: "PE", title: "Peru", label: "🇵🇪" },
  { value: "PH", title: "Philippines", label: "🇵🇭" },
  { value: "PL", title: "Poland", label: "🇵🇱" },
  { value: "PT", title: "Portugal", label: "🇵🇹" },
  { value: "PR", title: "Puerto Rico", label: "🇵🇷" },
  { value: "RO", title: "Romania", label: "🇷🇴" },
  { value: "RU", title: "Russia", label: "🇷🇺" },
  { value: "SA", title: "Saudi Arabia", label: "🇸🇦" },
  { value: "ZA", title: "South Africa", label: "🇿🇦" },
  { value: "KR", title: "South Korea", label: "🇰🇷" },
  { value: "ES", title: "Spain", label: "🇪🇸" },
  { value: "SE", title: "Sweden", label: "🇸🇪" },
  { value: "CH", title: "Switzerland", label: "🇨🇭" },
  { value: "TW", title: "Taiwan", label: "🇹🇼" },
  { value: "TH", title: "Thailand", label: "🇹🇭" },
  { value: "TR", title: "Turkey", label: "🇹🇷" },
  { value: "UA", title: "Ukraine", label: "🇺🇦" },
  { value: "GB", title: "United Kingdom", label: "🇬🇧" },
  { value: "US", title: "United States", label: "🇺🇸" },
  { value: "UY", title: "Uruguay", label: "🇺🇾" },
  { value: "VE", title: "Venezuela", label: "🇻🇪" },
  { value: "VN", title: "Vietnam", label: "🇻🇳" },
];
